### ISSUE TITLE
Problem on Compile

### ISSUE THREAD

**Issue by addisoncrump** [FMNSSun/Burlesque#1]
The compiler fails on step 4 of 6 of the process:

<pre>[1 of 6] Compiling Burlesque.Helpers ( Burlesque/Helpers.hs, Burlesque/Helpers.o )
[2 of 6] Compiling Burlesque.Types  ( Burlesque/Types.hs, Burlesque/Types.o )
[3 of 6] Compiling Burlesque.Display ( Burlesque/Display.hs, Burlesque/Display.o )
[4 of 6] Compiling Burlesque.Parser ( Burlesque/Parser.hs, Burlesque/Parser.o )

Burlesque/Parser.hs:242:1:
    Non type-variable argument
      in the constraint: Text.Parsec.Prim.Stream
                           s Data.Functor.Identity.Identity t
    (Use FlexibleContexts to permit this)
    When checking that ‘runParserWithString’ has the inferred type
      runParserWithString :: forall s t.
                             Text.Parsec.Prim.Stream s Data.Functor.Identity.Identity t =>
                             Text.Parsec.Prim.Parsec s () [BlsqExp] -> s -> [BlsqExp]

Burlesque/Parser.hs:247:1:
    Non type-variable argument
      in the constraint: Text.Parsec.Prim.Stream
                           s Data.Functor.Identity.Identity t
    (Use FlexibleContexts to permit this)
    When checking that ‘runParserWithString'’ has the inferred type
      runParserWithString' :: forall s t.
                              Text.Parsec.Prim.Stream s Data.Functor.Identity.Identity t =>
                              Text.Parsec.Prim.Parsec s () BlsqExp -> s -> BlsqExp</pre>

**Comment by FMNSSun** [comment]
What version of ghc are you using?

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3
$ ghc -o blsq -static -O3 main.hs
[1 of 6] Compiling Burlesque.Helpers ( Burlesque/Helpers.hs, Burlesque/Helpers.o )
[2 of 6] Compiling Burlesque.Types  ( Burlesque/Types.hs, Burlesque/Types.o )
[3 of 6] Compiling Burlesque.Display ( Burlesque/Display.hs, Burlesque/Display.o )
[4 of 6] Compiling Burlesque.Parser ( Burlesque/Parser.hs, Burlesque/Parser.o )
[5 of 6] Compiling Burlesque.Eval   ( Burlesque/Eval.hs, Burlesque/Eval.o )
[6 of 6] Compiling Main             ( main.hs, main.o ) [Burlesque.Eval changed]
```

You might try compiling it with `ghc -XFlexibleContexts -o blsq -static -O3 main.hs`. Does that work?

**Comment by FMNSSun** [comment]
Oh ok. Apparentely since `ghc 7.10` you need `FlexibleContexts`. I've added it as a `{-# ... -#}` so it must not be provided as a command line switch. If you pull the recent commit and compile again it should compile fine on 7.10 (or whatever exact version you have) without `-XFlexibleContexts`. Please tell me if that works.

**Comment by addisoncrump** [comment]
New, probably separate (although it still ties to FlexibleContents, obviously), compile issue:

<pre>
[1 of 6] Compiling Burlesque.Helpers ( Burlesque/Helpers.hs, Burlesque/Helpers.o )
[2 of 6] Compiling Burlesque.Types  ( Burlesque/Types.hs, Burlesque/Types.o )
[3 of 6] Compiling Burlesque.Display ( Burlesque/Display.hs, Burlesque/Display.o )
[4 of 6] Compiling Burlesque.Parser ( Burlesque/Parser.hs, Burlesque/Parser.o )
[5 of 6] Compiling Burlesque.Eval   ( Burlesque/Eval.hs, Burlesque/Eval.o )
Burlesque/Eval.hs:125:1:
    Non type-variable argument
      in the constraint: MonadState (t, t, t) m
    (Use FlexibleContexts to permit this)
    When checking that ‘putStack’ has the inferred type
      putStack :: forall (m :: * -> *) t t1 t2.
                  MonadState (t, t1, t2) m =>
                  t -> m ()
Burlesque/Eval.hs:133:1:
    Non type-variable argument
      in the constraint: MonadState (t, [a], t) m
    (Use FlexibleContexts to permit this)
    When checking that ‘pushStateStack’ has the inferred type
      pushStateStack :: forall (m :: * -> *) t t1 a.
                        MonadState (t, [a], t1) m =>
                        a -> m ()
Burlesque/Eval.hs:146:1:
    Non type-variable argument
      in the constraint: MonadState ([a], t, t) m
    (Use FlexibleContexts to permit this)
    When checking that ‘pushToStack’ has the inferred type
      pushToStack :: forall (m :: * -> *) t t1 a.
                     MonadState ([a], t, t1) m =>
                     a -> m ()
Burlesque/Eval.hs:155:1:
    Non type-variable argument
      in the constraint: MonadState ([a], t, t) m
    (Use FlexibleContexts to permit this)
    When checking that ‘pushToBottom’ has the inferred type
      pushToBottom :: forall (m :: * -> *) t t1 a.
                      MonadState ([a], t, t1) m =>
                      a -> m ()
Burlesque/Eval.hs:159:1:
    Non type-variable argument
      in the constraint: MonadState (t, t, M.Map k a) m
    (Use FlexibleContexts to permit this)
    When checking that ‘setVar’ has the inferred type
      setVar :: forall (m :: * -> *) t t1 k a.
                (Ord k, MonadState (t, t1, M.Map k a) m) =>
                k -> a -> m ()
Burlesque/Eval.hs:163:1:
    Non type-variable argument
      in the constraint: MonadState (t, t, M.Map k BlsqExp) m
    (Use FlexibleContexts to permit this)
    When checking that ‘getVar’ has the inferred type
      getVar :: forall (m :: * -> *) t t1 k.
                (Ord k, MonadState (t, t1, M.Map k BlsqExp) m) =>
                k -> m BlsqExp
</pre>

**Comment by addisoncrump** [comment]
Note that I'm using main_golf.hs, if this affects your solution in any way.

**Comment by FMNSSun** [comment]
Hm, guess I need to put FlexibleContexts everywhere.

**Comment by FMNSSun** [comment]
I've added `FlexibleContexts` to every file now.

**Comment by addisoncrump** [comment]
It compiles! Hooray!
There are still a few warnings, but that's (probably) okay. They're below, in case you want to see them.

<pre>[5 of 6] Compiling Burlesque.Eval   ( Burlesque/Eval.hs, Burlesque/Eval.o )
Burlesque/Eval.hs:594:1: Warning: Tab character
Burlesque/Eval.hs:595:1: Warning: Tab character
Burlesque/Eval.hs:596:1: Warning: Tab character
Burlesque/Eval.hs:597:1: Warning: Tab character
Burlesque/Eval.hs:598:1: Warning: Tab character
Burlesque/Eval.hs:599:1: Warning: Tab character
Burlesque/Eval.hs:600:1: Warning: Tab character
Burlesque/Eval.hs:601:1: Warning: Tab character
Burlesque/Eval.hs:602:1: Warning: Tab character
Burlesque/Eval.hs:3075:1: Warning: Tab character</pre>

**Comment by FMNSSun** [comment]
Looks like GHC devs have decided to 'ban' usage of tabs in code. Those are just warnings, code should work fine. I'll replace them with spaces in the next few commits. 

Let me know if you encounter any other issues (be it runtime crashes or wrong documentation or anything else. I'm happy to fix them.)

**Comment by addisoncrump** [comment]
Seems to work fine! Using ./shell.sh throws a whole bunch of warnings when it starts, but no errors. I'll let you know of any problems I have, thanks!

**Comment by FMNSSun** [comment]
That's because `shell.sh` does `runghc main.hs --shell` which invokes ghc every time.
If you don't want that compile the `main.hs` and pass `-shell`.

```
$ ghc -O3 -o blsq main.hs
[6 of 6] Compiling Main             ( main.hs, main.o )
Linking blsq ...
$ ./blsq --shell
blsq ) 

```

Doing `runghc` has a very slow start-up time.
