### ISSUE TITLE
burlesque shell moved

### ISSUE THREAD

**Issue by int-e** [FMNSSun/Burlesque#7]
The VM has moved to a new IP again

  http://64.137.173.192/~burlesque/burlesque.cgi

Alternatively, I've now given it a DNS name:

  http://cheap.int-e.eu/~burlesque/burlesque.cgi

On a related note, cgi.hs does not currently compile.

**Comment by FMNSSun** [comment]
Thanks :).

Do you have a compiler error log you could attach?

**Comment by FMNSSun** [comment]
Nvm. I found and fixed it. 
BTW: Burlesque now has I/O support but it's disabled by default now. If you want with I/O support you need to define `HAVE_IO_SHIT` for the `#ifdef HAVE_IO_SHIT` to kick in. For cgi you probably don't want IO but it's disabled by default.

**Comment by FMNSSun** [comment]
Done. Thanks again for hosting the shell.
