### ISSUE TITLE
typo in TUTORIAL.md

### ISSUE THREAD

**Issue by natethern** [FMNSSun/Burlesque#8]
"Burlesque treats 0 as false end everything else as false" should probably be "Burlesque treats 0 as false end everything else as true". If not, some more explanation in needed.

**Comment by FMNSSun** [comment]
Ah right. Thank you for reporting this.

**Comment by FMNSSun** [comment]
Should be fixed now.

**Comment by FMNSSun** [comment]
If you happen to stumble upon any other errors please report them as well. The [Moonpage](https://mroman.ch/burlesque/docs/BLSQ.html) is the most accurate documentation and contains examples but I never had the time to complete it (yet). The [language reference](https://mroman.ch/burlesque/lref.html) is the most complete documentation but it doesn't provide examples and explanations. 

Happy learning and have fun ;)
